### ISSUE TITLE
possible update of ESUN values

### ISSUE THREAD

**Issue by gillins** [ubarsc/python-fmask#15]
**[Original report](https://bitbucket.org/chchrsc/python-fmask/issue/15) by David Ketchum (Bitbucket: [dgketchum](https://bitbucket.org/dgketchum), GitHub: [dgketchum](https://github.com/dgketchum)).**

----------------------------------------

Hi, 
I love your project.  I was reading the source and came across the values for ESUN, which my need updating.  I'm probably missing something, but the values for Landsat 7 on fmask.LandsatTOA aren't as they appear at https://landsat.usgs.gov/esun.  I'm probably missing something that takes care of this.  Is this the case?

Thanks for all your work on fmask, it makes my life easier!

**Comment by neilflood** [comment]
This was three years ago, so presumably all OK. Plus, looks like OP has now implemented their own Fmask anyway. :-)
