### ISSUE TITLE
deprecation of pre-stacked sentinel2 processing

### ISSUE THREAD

**Issue by gillins** [ubarsc/python-fmask#22]
**[Original report](https://bitbucket.org/chchrsc/python-fmask/issue/22) by Ian Cooke (Bitbucket: [ircwaves](https://bitbucket.org/ircwaves), GitHub: [ircwaves](https://github.com/ircwaves)).**

----------------------------------------

First let me say that we are very grateful that you have contributed this fmask implementation to the open source world.  It is an excellent package that provides a key component for the python ecosystem for Sentinel-2 data users.

Version 0.5.0 indicates that passing `fmask_sentinel2Stacked.py` pre-stacked file of reflectance bands (`--toa`), and the image of angles (`--anglesfile`)  is obsoleted.   This use-case worked out very well for our application where we download the individual bands and the metadata XML, instead of the entire SAFE archive.

@vincentschut is mentioned [here](https://bitbucket.org/chchrsc/python-fmask/src/a9fb0ce1495412da5d9cd1b711d0c163752d5d2b/bin/fmask_sentinel2Stacked.py#lines-170:172) indicating that VRT-based resampling may result in pulling shifted data from the overviews.  We haven't observed any issue thus far, but perhaps a link to an example (or discussion) can be posted?  I've grappled with many resampling/registration issues, so I am quite familiar with how subtle they can be.

I've labelled this minor, as there are various options to work around, but I think it might be helpful for general understanding of the reason for this change.

Thanks,

Ian

**Comment by neilflood** [comment]
No further action required.
