### ISSUE TITLE
fmask usage

### ISSUE THREAD

**Issue by gillins** [ubarsc/python-fmask#26]
**[Original report](https://bitbucket.org/chchrsc/python-fmask/issue/26) by Anonymous.**

----------------------------------------

Hello,

I've just installed fmask to my python 2.7.
I'm going to use it to make cloud mask files and not familiar with cmd commands.
Could you please show me how to use fmask in scripts properly?

Regards,
Grigory

**Comment by neilflood** [comment]
Closing, assuming no further troubles.
