### ISSUE TITLE
add requiriments list to installation

### ISSUE THREAD

**Issue by eamanu** [ubarsc/python-fmask#31]
Hi, 

I try to install python-fmask in a clean venv and when I run the `fmask_sentinel2Stacked.py` give me error that `numpy, rios ...  ` are not installed. 

I can see the documentation  that say: `Installation requires Python, numpy, scipy, GDAL and RIOS` but maybe will be interest has that written on the README or just a requirements.txt file

**Comment by annamnara** [comment]
conda config --add channels conda-forge
conda config --set channel_priority strict
conda create -n myenv python-fmask
conda activate myenv

**Comment by eamanu** [comment]
I'm not working anymore with python-fmask, but during this opening issue I didn't
 use conda.

**Comment by neilflood** [comment]
Seems like this issue is only of historical interest, so I will close it.
