### ISSUE TITLE
unrecognized arguments

### ISSUE THREAD

**Issue by luanschimidel** [ubarsc/python-fmask#38]
Im tryng execute this comand : fmask_usgsLandsatStacked.py -o cloud.img scenedir LC08_L1TP_217076_20180901_20180912_01_T1 to get a LandSat-8 image whith de 5 classifications, but im having this error:
fmask_usgsLandsatStacked.py: error: unrecognized arguments: scenedir LC08_L1TP_217076_20180901_20180912_01_T1
im starting now to use fmask, and dont know how resolve this error

**Comment by neilflood** [comment]
It appears that you have left out the -- on the scenedir option
