### ISSUE TITLE
Using Fmask

### ISSUE THREAD

**Issue by luanschimidel** [ubarsc/python-fmask#39]
Hello, i would like know how i can use the fmask funcionalities associated whit a qgis code, for create a cloud mask

**Comment by neilflood** [comment]
This implementation of Fmask is a command-line tool, and a Python module for use by Python programmers. It is not connected to qgis. Someone else has used it to build an interactive qgis plugin, but I see that you have also asked a question there, too.

**Comment by luanschimidel** [comment]
@neilflood  I know this, but i'm trying use this funcionalities at by comand line, and i dont know how do it,. There's any tutorial that could pass me please?

**Comment by petebunting** [comment]
Examples of the command line tools are on the website: http://www.pythonfmask.org

e.g., 
`fmask_usgsLandsatStacked.py -o cloud.img --scenedir LC08_L1TP_150033_20150413_20170410_01_T1`

**Comment by luanschimidel** [comment]
Yes yes, but i need examples aren't for the python's terminal not the cmd. It's my doubt

**Comment by gillins** [comment]
You could launch the command line tools via Python's `subprocess` module. Otherwise there is some documentation of how to call the fmask internals directly from Python here: http://www.pythonfmask.org/en/latest/fmask_fmask.html#fmask.fmask.doFmask 

Don't think there are any examples though.

**Comment by neilflood** [comment]
It depends what you are trying to do. If you just want to run Fmask on the files supplied by ESA, then I recommend just using the command line tools. If you need to run this from inside another Python program, then do as @gillins suggests and use subprocess or similar, to call the command line tool. 

You should only need to work with the Python module if you want to be able to re-organise the data files in some way. This should only be attempted after a bit more experience than you seem to have at the moment. If you really need an example, the command line tools are a good place to start, as this is exactly what they do.

**Comment by neilflood** [comment]
One more thing - if you are having trouble, please show us what you are doing, and what error you get.
