### ISSUE TITLE
python-fmask and google colab

### ISSUE THREAD

**Issue by Rim-chan** [ubarsc/python-fmask#40]
Hey, I was wondering if the fmask can be implemented using google collab. So far I wasn't able to download it there using `!pip install python-fmask`.

**Comment by neilflood** [comment]
I don't know what google collab is.

However, we are unlikely to support installing with pip. The main problem is that pip is not smart enough to understand the dependencies on non-python packages like GDAL. Further discussion on this can be found under issue #30. 

You might consider using conda, which does understand the full dependency tree. See instructions at [https://www.pythonfmask.org/en/latest/#downloads](https://www.pythonfmask.org/en/latest/#downloads)
