### ISSUE TITLE
can not run version 0.5.5 

### ISSUE THREAD

**Issue by YimingZhang0708** [ubarsc/python-fmask#43]
Hi there,
It is so cool to publish the python version of Fmask. Thank you so much for your work. But I am wondering if the version 0.5.5 is also for Fmask4.0? And when I tried to run version 0.5.5, I got some errors:
1) in the file fillminia.py, Line 71，72, the fillMinima function have eight variables. But in the definition of this function, there are three variables.
2)in the file valueindex.py, Line 143，144, there is no function called valndxFunc.
Did I miss something or the code is not fully finished until now.
Thank you so much,
Yiming

**Comment by neilflood** [comment]
Hi Yiming,

The python-fmask4 repository was an experimental test of the Fmask4 algorithm. The README.md says this, and also says that it is not complete. It also says that the Fmask4 changes are in a separate branch, which you will need to checkout before trying to use it. 

After some testing with this implementation, we found it was not clear that the new algorithm was an improvement on the old one, and no further development was done. We have no plans to continue further with it. 

Neil

**Comment by YimingZhang0708** [comment]
Thank you so much for your reply! And then what version of Fmask is version 0.5.5 for? I have thought the version 0.5.5 is based on the 0.5.3.
Best,
Yiming

**Comment by YimingZhang0708** [comment]
Thank you so much for your reply! So is the version 0.5.5 is for Fmask before 4.0?
Best,
Yiming

**Comment by neilflood** [comment]
That is correct. The algorithm known as Fmask 4.0 involved a number of major changes, and implementing it in Python required a lot of changes to the code structure. As mentioned above, and as discussed on the front page at [https://www.pythonfmask.org](https://www.pythonfmask.org), we experimented with this in a separate repository, but have decided not to continue with it. The code in this repository is for the earlier published Fmask algorithm.

**Comment by YimingZhang0708** [comment]
Got it! Thank you so much for your clarification! I will try to run Fmask4.0 in another repository.
Best,
Yiming
