### ISSUE TITLE
Does python-fmask also need the auxiliary data？

### ISSUE THREAD

**Issue by hello-willy** [ubarsc/python-fmask#52]
Can you provide a download link if necessary, except Google driver, thank you!!!

**Comment by neilflood** [comment]
What auxiliary data? 

The released tar.gz or .zip are complete, and do not require anything else.

**Comment by hello-willy** [comment]
thank you for your reply!
from the https://github.com/GERSL/Fmask, i saw the content:
![1](https://user-images.githubusercontent.com/9379589/155672746-5b6b0519-1354-4f67-af70-2a194e5a49a0.png)

**Comment by neilflood** [comment]
I wondered if that was what you meant. That is a different algorithm, known as Fmask4. It was created by the same authors as the original Fmask algorithm, but does many things differently.

This package was written long before that, and implements their earlier algorithm, known as Fmask, and does not require any additional files. See [https://www.pythonfmask.org/](https://www.pythonfmask.org/) for a bit more detail, and references to the relevant published papers.

**Comment by hello-willy** [comment]
> I wondered if that was what you meant. That is a different algorithm, known as Fmask4. It was created by the same authors as the original Fmask algorithm, but does many things differently.
> 
> This package was written long before that, and implements their earlier algorithm, known as Fmask, and does not require any additional files. See https://www.pythonfmask.org/ for a bit more detail, and references to the relevant published papers.

I got it, thank you!!
