### ISSUE TITLE
About applying the generated mask back to the RGB file

### ISSUE THREAD

**Issue by xxie12** [ubarsc/python-fmask#57]
Hi,

I wonder if any function or command line can apply the mask to the original RGB file for sentinel 2? Thanks.

**Comment by neilflood** [comment]
No, we do not supply anything like that. This would be part of a more general set of tools for processing raster images. Some possible tools for this sort of thing include the Raster Calculator in QGIS, or the gdal_calc.py command in GDAL. For more flexible programming tools for raster processing, you could also look at GDAL's Python bindings, or tools like [rasterio](https://rasterio.readthedocs.io/) or [RIOS](https://www.rioshome.org/), which are both layered on top of GDAL.
