### ISSUE TITLE
Extract the snow/ice and water mask out from output .tif file

### ISSUE THREAD

**Issue by xxie12** [ubarsc/python-fmask#59]
Hi,

I am wondering if there is any way I can get snow, water, and cloud/cloud shadow mask separately or If there is any way I can extract a specific type of mask from the .tif output, thanks!

**Comment by neilflood** [comment]
No, we have not provided a mechanism for this style of output. You can easily process the resulting raster into separate layers using the sort of raster processing tools I mentioned in #57
