### ISSUE TITLE
Can I run fmask on tiff files?

### ISSUE THREAD

**Issue by jtsilverio** [ubarsc/python-fmask#65]
Hello,

I am currently trying to test fmask on some Sentinel-2 images I have. Currently, I am requesting images from sentinel-hub using the [`WcsRequest`](https://sentinelhub-py.readthedocs.io/en/latest/reference/sentinelhub.api.ogc.html?highlight=WcsRequest#sentinelhub.api.ogc.WcsRequest) request, which returns a .tiff file with a layer for each band for the area of interest provided.

This might be a very basic question but is it possible to run fmask on these .tiff files?

<br>

I know, by reading the docs, that you can you provide a .safe or granule directory when running fmask. However, since I am yet not very familiar with these kind of data I wanted to check if I can use the images I already have. Because if I can't I suppose I should change the way I am requesting the data and to obtain a .safe/granule directory.

Thanks :)

**Comment by neilflood** [comment]
Python-fmask also needs access to a couple of XML metadata files which are normally supplied with the full data bundle (known as a SAFE file). In principle you might get hold of those XML files, and combine those with the .tiff files you have, and be able to run, but you would need to know quite a bit about the details. 

So, my suggestion is that you start by acquiring SAFE files from [https://scihub.copernicus.eu/](https://scihub.copernicus.eu/). These are just zip files, and once you unzip one, you will have a SAFE directory, which you can give to the `--safedir` option on the python-fmask command line.

Once you are more familiar with the details, you might then revisit your plan to get the data from WcsRequest, if you are also able to source the metadata as well as the tiff files.

**Comment by jtsilverio** [comment]
Alright, thank for point me out in the right direction! I will get more familiar with the safe structure before trying other formats.

I am also closing the issue. :)
