### ISSUE TITLE
Unable to move the cache, Access denied 0x5

### ISSUE THREAD

**Issue by FrancescoSorrentino** [ubarsc/python-fmask#73]
Hello,
i've downloaded python-fmask-0.5.8 and used "pip install ." as is written in "INASTALL.txt".
When i use the command "`fmask_sentinel2Stacked.py -o cloud.img --safedir S2B_MSIL1C_20230505T100029_N0509_R122_T33SUC_20230505T120156.SAFE`" i get this error:

`[6584:0308/104510.522:ERROR:cache_util_win.cc(20)] Unable to move the cache: Accesso negato. (0x5)
[6584:0308/104510.522:ERROR:disk_cache.cc(205)] Unable to create cache`

**Comment by gillins** [comment]
Which operating system are you using? Windows?

**Comment by gillins** [comment]
And, what happens if you install via Conda Forge (see https://www.pythonfmask.org/en/latest/#downloads)? Does it work then?
There is a known issue with "pip install" and entrypoints on Windows with this package that we must fix...

**Comment by FrancescoSorrentino** [comment]
I'm trying to use the conda-forge version, now the cloud masking routine starts, but in the doCloudLayerFinalPass function of fmask.py, when the imagewriter of rios is called, and so the Driver_Create of gdal is called, i get this error:

`TypeError: invalid value for GDALDataType`

The command is the same as i wrote in the original comment of this issue, the .SAFE dir was downloaded from ESA Copernicus Hub.

**Comment by gillins** [comment]
@FrancescoSorrentino there is indeed a problem with fmask and recent GDAL we had not noticed. Can you make the change to `fmask.py` in your conda install to follow the one in https://github.com/ubarsc/python-fmask/pull/74 ?
